### ISSUE TITLE
sample application 

### ISSUE THREAD

**Issue by krystian566** [watsonpy/watson-framework#16]
test application is this same like start application?
Can some one can paste something?

**Comment by krystian566** [comment]
action="/"
Do not ask? I know.

I need only find whey to inject form. form ready function.

**Comment by simoncoulton** [comment]
Hey Krystian, 
I'm putting together a small sample application at the moment (complete with Gulp integration and a few other things), I'll put it up once it's done.

**Comment by krystian566** [comment]
I go up in my project.

**Comment by krystian566** [comment]
ssh and login session i whant to see how you do your implement

**Comment by BroukPytlik** [comment]
Anything new about the sample application? For the start, it would be nice to see a basic one. Just an example of few routes, a bit of html templates, one or two small models, and so on.

By the way, is there a way how to include a `{% block foo %}` from one view file in another?
For example, big part of `<head></head>` is the same on all pages, as well as some generic page structure... A top-level layout which is used first, and then its `{% block content %}` is filled by the specific view is a nice way how to simplify the code.

I suppose it should be possible, by the look of `TEMPLATE` in `views/renderers/jinja2.py`, but I can't find how to use it.

**Comment by simoncoulton** [comment]
Hey @BroukPytlik, I've just put up a basic Todo application at https://github.com/watsonpy/sample-todo-application which might give you a couple of ideas with regards to templating :)
