### ISSUE TITLE
cookies.get('name')

### ISSUE THREAD

**Issue by mrwert** [watsonpy/watson-framework#18]
Hello.

...cookies.get('name') -> return 'name=value'
How do I get only 'value'?

Thanks you for the Watson Framework.

**Comment by simoncoulton** [comment]
Hey @mrwert, you'll be able to retrieve them off the Request object via the following:

    Request.cookies['name']

Request.cookies returns a watson.http.cookies.CookieDict. Retrieving the cookie itself actually return a Morsel object which you can find the docs on that https://docs.python.org/2/library/cookie.html#Cookie.Morsel.

But basically:

    name = Request.cookies['name']
    name.value  # "value"
