### ISSUE TITLE
maturity stage of watson framework

### ISSUE THREAD

**Issue by Cad** [watsonpy/watson-framework#20]
What is the current maturity level of watson framework? Can it be used in production? And are there any applications that is powered by watson?

**Comment by simoncoulton** [comment]
Hey Cad, it definitely can be used in production. We've currently got it providing the REST APIs for quite a few of our iOS applications that we've built for clients. 
If you've got any specific questions regarding how Watson might suit your project shoot them through, more than happy to let you know if something else is more suitable :+1:

**Comment by Cad** [comment]
That's wonderful. I will definately use it for a simple project first. After getting comfortable with it I might use it for something more serious. I am not happy with the current state of the common python web frameworks. I was in the search of something better than them. Watson looks promising; and I got my answer. :)

**Comment by simoncoulton** [comment]
Excellent to hear, don't hesitate to submit a pull request if you come across anything issues.

**Comment by Cad** [comment]
:+1:
