### ISSUE TITLE
watson-console.py command not found

### ISSUE THREAD

**Issue by tkovalsky** [watsonpy/watson-framework#21]
either the documentation is missing some key elements, or the app is broken.

installed dependencies in virtualenv with pip.  when I go to generate the example project using

`watson-console.py project new sample.com.local`

I get this error:
`-bash: watson-console.py: command not found`

my requirements look like:
(watson) $ pip freeze
```
Jinja2==2.8
MarkupSafe==0.23
Pygments==1.6
watson-cache==1.1.0
watson-common==1.4.2
watson-console==2.0.2
watson-dev==3.0.0
watson-di==2.2.0
watson-events==1.0.3
watson-filters==1.0.0
watson-form==3.1.3
watson-framework==3.3.5
watson-html==1.2.0
watson-http==1.2.4
watson-mail==1.0.2
watson-routing==1.1.1
watson-validators==1.0.2
```

**Comment by simoncoulton** [comment]
Hi @tkovalsky, it's actually just `watson-console`. I've updated the docs to reflect this change in the next version.
