### ISSUE TITLE
Difference between "project name" and "app name" unclear

### ISSUE THREAD

**Issue by j-n-f** [watsonpy/watson-framework#22]
I'm looking at the documentation available here:
https://watson-framework.readthedocs.io/en/latest/getting-started/your-first-application.html

It's unclear how the project and app names should be thought of. It appears that the example given for a project name is a kind of namespacing. Are you able to clarify this at all?

My best guess is that I'd do something like `watson-console project new com.widgetcorp.xyz projectA`, and then any further apps for `com.widgetcorp.xyz` would use the same project name.

If I select some particular project name, is that just a value stored in one of watson's configuration files?

It's not critical for the purpose of making a sample app, but it would be helpful to understand the intention of "project name."

**Comment by simoncoulton** [comment]
Thanks for the input, basically you can think of the project name as being the top level directory for the project, and the app name as being the actual package that you'll reference in the code itself.

For example, if I was working on a project for xyz.widgetcorp.com I might run the following command: `watson-console project new com.widgetcorp.xyz widgetcorp`
This would end up giving me the following directory structure:

```
/com.widgetcorp.xyz
    /widgetcorp
    /public
        /js
        /css
...
```

I'll update the docs to reflect this point a little more clearly.

**Comment by j-n-f** [comment]
makes more sense now. Thank you for the clarification :)
