### ISSUE TITLE
Readthedocs page needs to get updated

### ISSUE THREAD

**Issue by habedi** [watsonpy/watson-framework#25]
Hi, 
Great framework guys;
But I think you need to update the docs in https://watson-framework.readthedocs.io/en/latest/getting-started/your-first-application.html because it seems that it should be like
```Bash
watson-console project new [project name] [app name]
```
instead of 
```Bash
watson-console.py project new [project name] [app name]
```

Cheers.

**Comment by simoncoulton** [comment]
Thanks! 
It is updated in the code, I'm not sure why readthedocs hasn't reflected this change, but I'll look into it!
